#!/usr/bin/env node

/**
 * Simple script to create .env file for the frontend
 * Usage: node create-env.js [backend-url]
 * Example: node create-env.js http://localhost:10000
 */

const fs = require('fs');
const path = require('path');

// Get backend URL from command line argument or use default
const backendUrl = process.argv[2] || 'http://localhost:10000';

const envContent = `# API Configuration
# Backend API base URL - auto-generated by create-env.js

# Current configuration
VITE_API_BASE_URL=${backendUrl}

# Other examples:
# Production: VITE_API_BASE_URL=https://your-api-domain.com
# Local network: VITE_API_BASE_URL=http://192.168.1.100:10000
`;

const envPath = path.join(__dirname, '.env');

try {
  // Check if .env already exists
  if (fs.existsSync(envPath)) {
    console.log('⚠️  .env file already exists!');
    console.log('📁 Location:', envPath);
    console.log('');
    console.log('Current content:');
    console.log(fs.readFileSync(envPath, 'utf8'));
    console.log('');
    
    // Ask if user wants to overwrite (basic check)
    const answer = process.argv.includes('--force') || process.argv.includes('-f');
    
    if (!answer) {
      console.log('ℹ️  To overwrite, run: node create-env.js --force');
      console.log('ℹ️  Or manually edit:', envPath);
      process.exit(0);
    }
    
    console.log('✅ Overwriting .env file...');
  }
  
  // Write .env file
  fs.writeFileSync(envPath, envContent, 'utf8');
  
  console.log('✅ .env file created successfully!');
  console.log('📁 Location:', envPath);
  console.log('');
  console.log('📝 Configuration:');
  console.log(`   VITE_API_BASE_URL=${backendUrl}`);
  console.log('');
  console.log('🚀 Next steps:');
  console.log('   1. Restart the frontend dev server: npm run dev');
  console.log('   2. Check browser console for: 🔗 API Base URL');
  console.log('   3. Verify API calls work');
  console.log('');
  console.log('💡 To change URL later:');
  console.log(`   - Edit: ${envPath}`);
  console.log('   - Restart dev server');
  console.log('');
  
} catch (error) {
  console.error('❌ Error creating .env file:', error.message);
  console.error('');
  console.error('💡 Manual steps:');
  console.error('   1. Create file: client/.env');
  console.error(`   2. Add line: VITE_API_BASE_URL=${backendUrl}`);
  console.error('   3. Restart dev server');
  process.exit(1);
}

